### ISSUE TITLE
Color doesn't change in preferences

### ISSUE THREAD

**Issue by atebitsy-old** [CreatureSurvive/libCSColorPicker#1]
when changing the color in eclipse x preferences and some other preferences using CSColorPicker the color doesnt change

**Comment by CreatureSurvive** [comment]
Fixed in [7e14ec9](https://github.com/CreatureSurvive/libCSColorPicker/commit/7e14ec90a83c21f1c76359c30e617f51cf1e6459) issue was due to saving with incorrect preference key.

**Comment by atebitsy-old** [comment]
perfect thank you very much:)
